# Fill in your logo address (darkmode and lightmode) here
# Dont forget to enable it.
# ------------------------------------------------------------
# åœ¨è¿™é‡Œå¡«å…¥ä½ çš„ Logo åœ°å€ - åŒ…æ‹¬é»‘æš—/ç™½å¤©æ¨¡å¼
# ä¸è¦å¿˜è®°æŠŠ enable æ”¹æˆ true å“¦ï½
logo:
  enable: true
  lightmode: https://oss.utc3.live/logo/lightmode.svg
  darkmode: https://oss.utc3.live/logo/darkmode.svg
  rss: https://oss.utc3.live/logo/logo.jpg

# Header size
# Select from: ["fullheight", "large", "medium", "default"]
# The page will be scroll to post thumbnail if autoscroll enabled
# ------------------------------------------------------------
# é€‰æ‹© Header çš„å¤§å°
# ä»å¤§åˆ°å°ä¾æ¬¡å¯ä»¥é€‰æ‹©ï¼š["fullheight", "large", "medium", "default"]
# å¦‚æœå¯ç”¨ autoscroll åœ¨è¿›å…¥æ–‡ç« åä¼šè‡ªåŠ¨è·³è½¬è‡³æ–‡ç«  Thumbnail å¤„
header:
  index: medium
  other: default
  autoscroll: true

# Favicon file link
# ------------------------------------------------------------
# Favicon æ–‡ä»¶åœ°å€
favicon: https://oss.utc3.live/favicon.ico

# Datetime format for most of positions
# ------------------------------------------------------------
# ç«™ç‚¹å†…å¤§éƒ¨åˆ†æ—¥æœŸçš„æ˜¾ç¤ºæ ¼å¼
timeformat: "MMM, D YYYY"

# Enable Podcast support or not
# æ˜¯å¦å¯ç”¨ Podcast æ”¯æŒ
podcast: true

# Enable Lazyload support or not
# ------------------------------------------------------------
# æ˜¯å¦å¯ç”¨å›¾ç‰‡æ‡’åŠ è½½
lazyload: true

# Your Copyright String will be shown in footer
# ------------------------------------------------------------
# ä½ çš„ç‰ˆæƒä¿¡æ¯ä¼šæ˜¾ç¤ºåœ¨é¡µè„š
copyright: 'ä¿ç•™æ‰€æœ‰æƒåˆ©.'

# Enable code auto Highlight or not
# Then select one lightmode and darkmode style here:
# https://github.com/highlightjs/highlight.js/tree/main/src/styles
# Please enable 'highlight' in your project _config.yml with 'hljs' field set to true!
# ------------------------------------------------------------
# æ˜¯å¦å¯ç”¨ä»£ç æ¸²æŸ“
# ä¹‹åç»™ä»£ç æ¸²æŸ“é€‰æ‹©ä¸€ä¸ªå¤œé—´/ç™½å¤©æ¨¡å¼ä¸»é¢˜ï¼š
# https://github.com/highlightjs/highlight.js/tree/main/src/styles
# æœ€åï¼Œåœ¨é¡¹ç›®çš„ _config.yml ä¸­æ‰“å¼€ highlight åŠŸèƒ½å¹¶æŠŠ hljs è®¾ç½®ä¸º trueï¼
highlight:
  enable: true
  lightmode: 'atom-one-light'
  darkmode: 'atom-one-dark'

# Navbar will be shown below your logo with some favicons
# You can select your icons with font-awesome 5
# Config format:
#   ['Link Address', 'Icon Class', 'Text After Icon']
# ------------------------------------------------------------
# Navbar ä¼šå±•ç¤ºåœ¨é¡µé¢å¤´éƒ¨çš„ Logo ä¸‹æ–¹
# ä½ å¯ä»¥å» Font Awesome 5 ä¸Šé¢é€‰ä¸€äº›å¥½çœ‹çš„å›¾æ ‡
# é…ç½®æ ¼å¼ï¼š
#   ['é“¾æ¥åœ°å€', 'å›¾æ ‡ç±»', 'å›¾æ ‡ä¹‹åçš„æ–‡å­—']
navbar: null

# Subnav configuration will show below navbar with a horizontal divider
# Configuration format as same as previous
# ------------------------------------------------------------
# Sub Navbar å°†ä¼šåœ¨ Navbar ä¸‹æ–¹å±•ç¤ºå¹¶ä»¥æ°´å¹³çº¿ä¸ä¹‹åˆ†å‰²
# é…ç½®æ¨¡å¼ä¸ä¸Šé¢ç±»ä¼¼
subnav:
  - ['/feed.rss', 'fa fa-rss', 'RSS è®¢é˜…']
  - ['https://podcasts.apple.com/us/podcast/æµæµªä¸œä¸‰åŒº/id1567397528', 'fa fa-podcast', 'Apple Podcast']
  - ['https://podcasts.apple.com/cn/podcast/æµæµªä¸œä¸‰åŒº/id1569145430', 'fa fa-podcast', 'å›½åŒº Apple Podcast']
  - ['https://podcasts.google.com/feed/aHR0cHM6Ly91dGMzLmxpdmUvZmVlZC5yc3M', 'fa fa-google', 'Google Podcast']
  - ['https://ximalaya.com/album/49806301', 'fa fa-headphones', 'å–œé©¬æ‹‰é›…']
  - ['https://www.xiaoyuzhoufm.com/podcast/60ae12317f5973eb92212a78?s=eyJ1IjogIjYwOWQxNjJmZTBmNWU3MjNiYjRlNGExYSJ9', 'fa fa-space-shuttle', 'å°å®‡å®™ FM']
  - ['https://overcast.fm/itunes1567397528', 'fa fa-bullseye', 'Overcast']
  - ['https://moon.fm/share/podcast/6285/ğŸ™æµæµªä¸œä¸‰åŒº', 'fa fa-moon-o', 'Moon FM']
  - ['https://open.spotify.com/show/3JzbdsCw7p8NvzZG8Vusui', 'fa fa-spotify', 'Spotify']
  - ['mailto:privet@utc3.live', 'fa fa-envelope', 'è”ç³»æˆ‘ä»¬']

# Menubar and its texts
# ------------------------------------------------------------
# èœå•æ çš„åœ°å€å’Œæ–‡å­—
menubar:
  - ['/about/', 'å…³äº']
  - ['/archives/', 'å½’æ¡£']

# RSS auto generation configuration
#   enable: true or false
#   path: feeding path
#   config:
#     email: your podcast contact email
#     category: {
#       'Apple Podcast Category name': ['Subcategories', ...],
#       ...
#     }
#     explicit: using true if your podcast content is explicit
# ------------------------------------------------------------
# RSS è‡ªåŠ¨ç”Ÿæˆå™¨é…ç½®
#   enable: å¯ç”¨ä¸º true
#   path: RSS è®¢é˜…åœ°å€
#   config:
#     email: ä½ çš„ Podcast è”ç³»é‚®ç®±
#     category: {
#       'Apple Podcast åˆ†ç±»å': ['å­åˆ†ç±»åˆ—è¡¨', ...],
#       ...
#     }
#     explicit: å¦‚æœä½ çš„æ’­å®¢æœ‰ç¾ç¾çš„å†…å®¹ï¼Œé‚£ä¹ˆæ”¹æˆ true
rss:
  enable: true
  path: '/feed.rss'
  config:
    email: 'privet@utc3.live'
    category: {
      'Education': ['How To', 'Language Learning'],
      'Technology': []
    }
    explicit: false

# Boardcast info will show in top of the post list
# Color:
#   default: grey
#   danger: red
#   info: blue
#   warning: yellow
# ------------------------------------------------------------
# ç«™ç‚¹æ¶ˆæ¯å¹¿æ’­ - ä¼šæ˜¾ç¤ºåœ¨é¦–é¡µçš„æ–‡ç« åˆ—è¡¨é¡¶éƒ¨
# å¹¿æ’­å—é¢œè‰²é€‰æ‹©:
#   default: ç°è‰²
#   danger: çº¢è‰²
#   info: è“è‰²
#   warning: é»„è‰²
boardcast: 
  enable: false
  color: default
  message: 'çºªå¿µè¢éš†å¹³é™¢å£«ã€‚'

# Site mourn mode, enable to get a global grayscale filter
# ------------------------------------------------------------
# ç«™ç‚¹æ‚¼å¿µæ¨¡å¼ - å¯ç”¨åä¼šä¸ºç«™ç‚¹æ•´ä½“æä¾›ç°è‰²æ»¤é•œ
mourn: false
